<a href="https://colab.research.google.com/github/kambrosgroup/Python.Programming/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy Notebook.

## Demonstrating knowledge of numpy package use.

### What is numpy?

One of the key features of NumPy is its N-dimensitional array object or short for ndarraym which is a fast, flexiable container for large data sets in python. it allows you to perform mathematical operations on whole block of data using similar syntax to the equivalent operation between scalar elements. 

for example:

In [4]:
#import package to the enviroment.
import numpy as np

#create np data
data1  = np.arange(15).reshape(3, 5)

#shape of the data
print("shape:", data1.shape)
#number of dimension 
print("Dimension:", data1.ndim)
#size
print("size:", data1.size)
#type
print("type:", type(data1))

shape: (3, 5)
Dimension: 2
size: 15
type: <class 'numpy.ndarray'>


### creating ndarray

there are several ways of creating ndarrays but the easiest one is through array function. this accepts any sequence-like object.

In [17]:
#using array function
data2 = [6,4,7,2,5,0,1]
print("Before:", data2)
array1 = np.array(data2)
print("After:", array1)

#alternative
data2 = np.array([6,4,7,2,5,0,1])
print("alternative",data2)

#built-in zeros and ones 
data2 = np.zeros(10)
print("zeros:",data2)
data2 = np.ones(10)
print("ones:",data2)

#built-in range
data2 = np.arange(15)
print("arange:",data2)

Before: [6, 4, 7, 2, 5, 0, 1]
After: [6 4 7 2 5 0 1]
alternative [6 4 7 2 5 0 1]
zeros: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
ones: [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
arange: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


we can also make multi dimensitional array and explicitly specify the dtype

In [37]:
#two dimension
data2 = np.array([(4,7,2,1,5),(9,1,0,4,2)])
print("2-dimension: \n",data2)
print()

#five dimension
data2 = np.array([(4,7,2,1,5),
                  (9,1,0,4,2),
                  (2,4,3,7,1),
                  (7,6,3,1,2),
                  (4,1,9,4,2)], dtype=np.int32) #32-bit integer
print("5-dimension: \n",data2)
print()

#dtype change
data2 = np.array([(4,7,2,1,5),
                  (9,1,0,4,2),
                  (2,4,3,7,1),
                  (7,6,3,1,2),
                  (4,1,9,4,2)], dtype=np.complex128) #128-bit complex floating point number
print("5-dimension(dtype=complex128): \n",data2)

#cast or convert array
data2 = np.arange(10.0)
print(data2.dtype, data2)
print()
#convert to int32
data2 = data2.astype(np.int32)
print(data2.dtype, data2)
print()
#convert int to string
num_string = np.array(['1.25','9.4','-8.27'], dtype=np.string_)
print(num_string)
num_string = num_string.astype(float)
print(num_string)
#convert int to unicode
data2 = data2.astype(np.unicode_)
print(data2.dtype, data2)
print()

2-dimension: 
 [[4 7 2 1 5]
 [9 1 0 4 2]]

5-dimension: 
 [[4 7 2 1 5]
 [9 1 0 4 2]
 [2 4 3 7 1]
 [7 6 3 1 2]
 [4 1 9 4 2]]

5-dimension(dtype=complex128): 
 [[4.+0.j 7.+0.j 2.+0.j 1.+0.j 5.+0.j]
 [9.+0.j 1.+0.j 0.+0.j 4.+0.j 2.+0.j]
 [2.+0.j 4.+0.j 3.+0.j 7.+0.j 1.+0.j]
 [7.+0.j 6.+0.j 3.+0.j 1.+0.j 2.+0.j]
 [4.+0.j 1.+0.j 9.+0.j 4.+0.j 2.+0.j]]
float64 [0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]

int32 [0 1 2 3 4 5 6 7 8 9]

[b'1.25' b'9.4' b'-8.27']
[ 1.25  9.4  -8.27]
<U11 ['0' '1' '2' '3' '4' '5' '6' '7' '8' '9']



### Operation between arrays and scalars
Arrays are important because they enable us to express bacth operations on data without any for loops. this is called vectorization and any arithmetic operations between equal-size array applies element-wise. suppose we wanted to multiply two arrays with same size.

In [49]:
array1 = np.arange(15).reshape(3,5) #3 by 5 multi-dimension array
print(array1)
print()
array2 = np.arange(15).reshape(3,5) ** 3 #3 by 5 multi-dimension array to the power of 3
print(array2)
print()
array3 = array1*array2 # multiply array1 and array2 elementwise
print(array3)
print()
array3 = array1+array2 #add
print(array3)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]

[[   0    1    8   27   64]
 [ 125  216  343  512  729]
 [1000 1331 1728 2197 2744]]

[[    0     1    16    81   256]
 [  625  1296  2401  4096  6561]
 [10000 14641 20736 28561 38416]]

[[   0    2   10   30   68]
 [ 130  222  350  520  738]
 [1010 1342 1740 2210 2758]]


### Basic indexing and slicing.

numpy array indexing is a rich topic, as there are many ways you may want to select a subset of your data or individual elements. one-dimensional array can be sliced, indexed and iterated over much like list and other python sequences. 